spring:
  application:
    name: driftwood
  datasource:
    url: jdbc:postgresql://localhost:5432/driftwood
    username: driftwood
    password: driftwood
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: driftwood
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.driftwood.messaging"

server:
  port: 8080

driftwood:
  worker:
    failure-rate: 0.0
    step-failure-rates:
      flaky-workflow-step-2: 0.3
    step-failures:
      poison-workflow-step-2: 99
